### ISSUE TITLE
Card | Dialog component

### ISSUE THREAD

**Issue by josssp** [nastyasap/components#1]
Добрый день, не могли бы вы сделать компонент **Card | Dialog**. В полноценном виде.

Наверное компонент должен принимать контент как children, чтобы быть переиспользуемым.

**Comment by nastyasap** [comment]
Добрый день, сейчас переделаю

пн, 5 дек. 2022 г. в 14:37, Joss ***@***.***>:

**Comment by nastyasap** [comment]
Поправила пропсы https://github.com/nastyasap/components

пн, 5 дек. 2022 г. в 14:44, Анастасия Сапожникова ***@***.***>:

**Comment by josssp** [comment]
@nastyasap я сделал pull request для уточнения

**Comment by nastyasap** [comment]
@josssp cделала через children, но добавила еще одну компоненту Card
